#!/usr/bin/env python
import argparse

import cv2 as cv


def main():

    parser = argparse.ArgumentParser(description='Count frames in video file.')

    parser.add_argument('video', metavar='F',
                        help='Video file to read in.')

    args = parser.parse_args()

    cap = cv.VideoCapture(args.video)
    #length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    frames = 0
    while(cap.isOpened()):
        stat, _ = cap.read()
        if not stat:
            break
        frames += 1
    print(f'{frames} frames in file')

if __name__ == '__main__':
    main()


